<a href="https://colab.research.google.com/github/AndrewDem04/pyTorch_fundamentals/blob/main/00_pyTorch_fundamentals.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [115]:
import torch
print(torch.__version__)

2.6.0+cu124


## Introduction to Tensors


### scaral

In [116]:
# we have difrente types of tensors
#You must see the -- torch.tensor documentation and what tensor is
# scaral

scalar = torch.tensor(7)
scalar.item()

7

### vector

In [117]:
# vector
vector = torch.tensor([7,7])
vector

tensor([7, 7])

In [118]:
# how meny dimension it have --ndim
vector.ndim

1

In [119]:
vector.shape

torch.Size([2])

In [120]:
MATRIX = torch.tensor([[7,8],[9,10]])

In [121]:
MATRIX.ndim

2

In [122]:
MATRIX[1]

tensor([ 9, 10])

In [123]:
MATRIX.shape

torch.Size([2, 2])

In [124]:
TENSOR = torch.tensor([[[1,2,3],[4,5,6],[7,8,9]]])

In [125]:
TENSOR.ndim

3

In [126]:
TENSOR.shape

torch.Size([1, 3, 3])

###### Lets create one more tensor and expiramend with the ndim , shape and the indexing

In [140]:
MYTENSOR = torch.tensor([[[1,2,3],[5,6,8],[2,5,6]],[[4,2,3],[5,66,8],[2,5,6]]])

In [141]:
MYTENSOR.shape

torch.Size([2, 3, 3])

In [142]:
MYTENSOR.ndim

3

In [143]:
MYTENSOR[0]

tensor([[1, 2, 3],
        [5, 6, 8],
        [2, 5, 6]])

In [144]:
MYTENSOR[1]

tensor([[ 4,  2,  3],
        [ 5, 66,  8],
        [ 2,  5,  6]])

In [145]:
MYTENSOR[1,1]

tensor([ 5, 66,  8])