<a href="https://colab.research.google.com/github/AndrewDem04/pyTorch_fundamentals/blob/main/00_pyTorch_fundamentals.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [115]:
import torch
print(torch.__version__)

2.6.0+cu124


## Introduction to Tensors


### scaral

In [116]:
# we have difrente types of tensors
#You must see the -- torch.tensor documentation and what tensor is
# scaral

scalar = torch.tensor(7)
scalar.item()

7

### vector

In [117]:
# vector
vector = torch.tensor([7,7])
vector

tensor([7, 7])

In [118]:
# how meny dimension it have --ndim
vector.ndim

1

In [119]:
vector.shape

torch.Size([2])

In [120]:
MATRIX = torch.tensor([[7,8],[9,10]])

In [121]:
MATRIX.ndim

2

In [122]:
MATRIX[1]

tensor([ 9, 10])

In [123]:
MATRIX.shape

torch.Size([2, 2])

In [124]:
TENSOR = torch.tensor([[[1,2,3],[4,5,6],[7,8,9]]])

In [125]:
TENSOR.ndim

3

In [126]:
TENSOR.shape

torch.Size([1, 3, 3])

###### Lets create one more tensor and expiramend with the ndim , shape and the indexing

In [140]:
MYTENSOR = torch.tensor([[[1,2,3],[5,6,8],[2,5,6]],[[4,2,3],[5,66,8],[2,5,6]]])

In [141]:
MYTENSOR.shape

torch.Size([2, 3, 3])

In [142]:
MYTENSOR.ndim

3

In [143]:
MYTENSOR[0]

tensor([[1, 2, 3],
        [5, 6, 8],
        [2, 5, 6]])

In [144]:
MYTENSOR[1]

tensor([[ 4,  2,  3],
        [ 5, 66,  8],
        [ 2,  5,  6]])

In [145]:
MYTENSOR[1,1]

tensor([ 5, 66,  8])

### Random tensors

Random tensors are important because many neural networks:

-start with random numbers
-look at data
-update random numbers
-look at data
-update

In [146]:
# create random tensor size (3,4)

random_tensor = torch.rand(3,4)
random_tensor

tensor([[0.2340, 0.7795, 0.3199, 0.8131],
        [0.0534, 0.1105, 0.1944, 0.6161],
        [0.2372, 0.5719, 0.9677, 0.4380]])

In [147]:
random_tensor.ndim

2

In [148]:
random_tensor.shape

torch.Size([3, 4])

In [150]:
# Create a random tensor with similar shape to an image tensor
random_image_size_tensor = torch.rand(size=(224,224,3)) # height,width , color channels (R,G,B)
random_image_size_tensor

tensor([[[0.9871, 0.8121, 0.0419],
         [0.4271, 0.7384, 0.1986],
         [0.6772, 0.6203, 0.9423],
         ...,
         [0.6351, 0.6312, 0.9178],
         [0.3270, 0.2796, 0.9143],
         [0.3283, 0.2088, 0.8481]],

        [[0.2668, 0.5152, 0.0962],
         [0.0328, 0.7667, 0.3237],
         [0.5567, 0.7329, 0.2002],
         ...,
         [0.9014, 0.9523, 0.4908],
         [0.5373, 0.6661, 0.5476],
         [0.0543, 0.4173, 0.0526]],

        [[0.2453, 0.7237, 0.4930],
         [0.5884, 0.2215, 0.5425],
         [0.3271, 0.3384, 0.4013],
         ...,
         [0.3579, 0.8875, 0.4731],
         [0.2484, 0.4048, 0.2696],
         [0.5562, 0.7207, 0.1049]],

        ...,

        [[0.5644, 0.6018, 0.0457],
         [0.4237, 0.2122, 0.5958],
         [0.1999, 0.7135, 0.8747],
         ...,
         [0.9848, 0.9184, 0.3131],
         [0.4073, 0.6586, 0.4279],
         [0.5838, 0.0086, 0.5577]],

        [[0.6262, 0.9741, 0.6071],
         [0.0747, 0.9263, 0.0697],
         [0.

In [151]:
random_image_size_tensor.shape , random_image_size_tensor.ndim

(torch.Size([224, 224, 3]), 3)

In [153]:
# lets create my own random tensor

myrandom_tensor = torch.rand(34,3,3,43)
myrandom_tensor

tensor([[[[0.3581, 0.3259, 0.9014,  ..., 0.3467, 0.0955, 0.0637],
          [0.9285, 0.4054, 0.9839,  ..., 0.4727, 0.0140, 0.4811],
          [0.8145, 0.4171, 0.0796,  ..., 0.5590, 0.8140, 0.4891]],

         [[0.0730, 0.0898, 0.6168,  ..., 0.2853, 0.0807, 0.7625],
          [0.8368, 0.3369, 0.1355,  ..., 0.2728, 0.9137, 0.1149],
          [0.7611, 0.6846, 0.7412,  ..., 0.3295, 0.6021, 0.5227]],

         [[0.3780, 0.1654, 0.3687,  ..., 0.7235, 0.9151, 0.7659],
          [0.4175, 0.3096, 0.9776,  ..., 0.2799, 0.0463, 0.3073],
          [0.2286, 0.6139, 0.6727,  ..., 0.9264, 0.3822, 0.3216]]],


        [[[0.0641, 0.3400, 0.3665,  ..., 0.1752, 0.7119, 0.0715],
          [0.1829, 0.3567, 0.5079,  ..., 0.5831, 0.7926, 0.4082],
          [0.2628, 0.8915, 0.4645,  ..., 0.8169, 0.7385, 0.9375]],

         [[0.8327, 0.8186, 0.4349,  ..., 0.9268, 0.9124, 0.9936],
          [0.7623, 0.8551, 0.3471,  ..., 0.4705, 0.9483, 0.9380],
          [0.2441, 0.7329, 0.8890,  ..., 0.8299, 0.3008, 0.5895]],

In [154]:
myrandom_tensor.shape , myrandom_tensor.ndim

(torch.Size([34, 3, 3, 43]), 4)