<a href="https://colab.research.google.com/github/AndrewDem04/pyTorch_fundamentals/blob/main/00_pyTorch_fundamentals.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [5]:
import torch
print(torch.__version__)

2.6.0+cu124


## Introduction to Tensors


### scaral

In [6]:
# we have difrente types of tensors
#You must see the -- torch.tensor documentation and what tensor is
# scaral

scalar = torch.tensor(7)
scalar.item()

7

### vector

In [7]:
# vector
vector = torch.tensor([7,7])
vector

tensor([7, 7])

In [8]:
# how meny dimension it have --ndim
vector.ndim

1

In [9]:
vector.shape

torch.Size([2])

In [10]:
MATRIX = torch.tensor([[7,8],[9,10]])

In [11]:
MATRIX.ndim

2

In [12]:
MATRIX[1]

tensor([ 9, 10])

In [13]:
MATRIX.shape

torch.Size([2, 2])

In [14]:
TENSOR = torch.tensor([[[1,2,3],[4,5,6],[7,8,9]]])

In [15]:
TENSOR.ndim

3

In [16]:
TENSOR.shape

torch.Size([1, 3, 3])

###### Lets create one more tensor and expiramend with the ndim , shape and the indexing

In [17]:
MYTENSOR = torch.tensor([[[1,2,3],[5,6,8],[2,5,6]],[[4,2,3],[5,66,8],[2,5,6]]])

In [18]:
MYTENSOR.shape

torch.Size([2, 3, 3])

In [19]:
MYTENSOR.ndim

3

In [20]:
MYTENSOR[0]

tensor([[1, 2, 3],
        [5, 6, 8],
        [2, 5, 6]])

In [21]:
MYTENSOR[1]

tensor([[ 4,  2,  3],
        [ 5, 66,  8],
        [ 2,  5,  6]])

In [22]:
MYTENSOR[1,1]

tensor([ 5, 66,  8])

### Random tensors

Random tensors are important because many neural networks:

-start with random numbers
-look at data
-update random numbers
-look at data
-update

In [23]:
# create random tensor size (3,4)

random_tensor = torch.rand(3,4)
random_tensor

tensor([[0.5189, 0.2800, 0.8231, 0.2387],
        [0.6133, 0.9284, 0.7183, 0.3298],
        [0.7033, 0.7990, 0.6061, 0.3048]])

In [24]:
random_tensor.ndim

2

In [25]:
random_tensor.shape

torch.Size([3, 4])

In [26]:
# Create a random tensor with similar shape to an image tensor
random_image_size_tensor = torch.rand(size=(224,224,3)) # height,width , color channels (R,G,B)
random_image_size_tensor

tensor([[[0.3364, 0.5157, 0.8356],
         [0.7282, 0.8302, 0.1320],
         [0.4649, 0.7586, 0.1817],
         ...,
         [0.4224, 0.9292, 0.4512],
         [0.0296, 0.9719, 0.5384],
         [0.3920, 0.5761, 0.3265]],

        [[0.2192, 0.5566, 0.3761],
         [0.0623, 0.8876, 0.7262],
         [0.8166, 0.3185, 0.4224],
         ...,
         [0.5283, 0.7826, 0.5625],
         [0.0179, 0.3523, 0.1841],
         [0.0932, 0.2120, 0.3800]],

        [[0.7327, 0.2407, 0.6035],
         [0.7227, 0.3092, 0.9654],
         [0.1109, 0.4617, 0.9259],
         ...,
         [0.3911, 0.4456, 0.1672],
         [0.2775, 0.1449, 0.3556],
         [0.2060, 0.0435, 0.9807]],

        ...,

        [[0.3944, 0.7507, 0.5664],
         [0.5881, 0.1986, 0.8681],
         [0.2893, 0.8398, 0.5197],
         ...,
         [0.0955, 0.6978, 0.2235],
         [0.5745, 0.4998, 0.0962],
         [0.8517, 0.6628, 0.9497]],

        [[0.5962, 0.0889, 0.6125],
         [0.2651, 0.9899, 0.6367],
         [0.

In [27]:
random_image_size_tensor.shape , random_image_size_tensor.ndim

(torch.Size([224, 224, 3]), 3)

In [28]:
# lets create my own random tensor

myrandom_tensor = torch.rand(34,3,3,43)
myrandom_tensor

tensor([[[[0.0176, 0.4075, 0.9305,  ..., 0.7108, 0.7272, 0.3177],
          [0.5246, 0.1057, 0.0845,  ..., 0.9683, 0.5629, 0.5423],
          [0.9099, 0.7200, 0.0933,  ..., 0.4691, 0.3516, 0.2542]],

         [[0.1189, 0.1662, 0.0125,  ..., 0.4596, 0.9230, 0.3520],
          [0.3307, 0.4351, 0.1413,  ..., 0.5952, 0.3462, 0.2750],
          [0.4366, 0.6538, 0.7617,  ..., 0.3785, 0.3703, 0.8148]],

         [[0.6454, 0.8395, 0.7086,  ..., 0.9309, 0.1436, 0.0252],
          [0.9286, 0.2622, 0.0319,  ..., 0.9961, 0.0462, 0.3106],
          [0.8597, 0.0698, 0.8274,  ..., 0.0946, 0.1970, 0.1977]]],


        [[[0.8673, 0.9415, 0.9451,  ..., 0.3057, 0.8595, 0.7060],
          [0.8027, 0.3189, 0.2167,  ..., 0.0700, 0.0573, 0.9931],
          [0.3854, 0.6799, 0.6503,  ..., 0.6474, 0.3236, 0.7548]],

         [[0.1674, 0.5340, 0.2242,  ..., 0.4727, 0.5896, 0.6797],
          [0.0625, 0.0646, 0.4348,  ..., 0.9544, 0.9520, 0.5665],
          [0.3028, 0.4029, 0.8864,  ..., 0.4562, 0.7091, 0.0540]],

In [29]:
myrandom_tensor.shape , myrandom_tensor.ndim

(torch.Size([34, 3, 3, 43]), 4)

# ZEROS AND ONES

In [32]:
ZEROS_TENSOR = torch.zeros(size =(2,3))
ZEROS_TENSOR

tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [33]:
ONES_TENSOR = torch.ones(2,3)
ONES_TENSOR , ONES_TENSOR.dtype

(tensor([[1., 1., 1.],
         [1., 1., 1.]]),
 torch.float32)

### Creating a range of tensors and tensors-like

In [44]:
# Lets use torch.arange() the old functions was range()

one_to_ten = torch.arange(start=1,end= 11)
one_to_ten

tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [41]:
with_steps = torch.arange(start=1,end= 11 , step= 3)
with_steps

tensor([ 1,  4,  7, 10])

In [45]:
# Creating tensors  like

ten_zeros = torch.zeros_like(input=one_to_ten)
ten_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

### Tensor datatypes

In [47]:
# Float 32 tensor

float_32_tensor = torch.tensor([3.0,6.0,9.0], dtype=None,
                               device=None,
                               requires_grad=False)
float_32_tensor

tensor([3., 6., 9.])