<a href="https://colab.research.google.com/github/AndrewDem04/pyTorch_fundamentals/blob/main/00_pyTorch_fundamentals.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [4]:
import torch
print(torch.__version__)

2.6.0+cu124


## Introduction to Tensors


### scaral

In [5]:
# we have difrente types of tensors
#You must see the -- torch.tensor documentation and what tensor is
# scaral

scalar = torch.tensor(7)
scalar.item()

7

### vector

In [6]:
# vector
vector = torch.tensor([7,7])
vector

tensor([7, 7])

In [7]:
# how meny dimension it have --ndim
vector.ndim

1

In [8]:
vector.shape

torch.Size([2])

In [9]:
MATRIX = torch.tensor([[7,8],[9,10]])

In [10]:
MATRIX.ndim

2

In [11]:
MATRIX[1]

tensor([ 9, 10])

In [12]:
MATRIX.shape

torch.Size([2, 2])

In [13]:
TENSOR = torch.tensor([[[1,2,3],[4,5,6],[7,8,9]]])

In [14]:
TENSOR.ndim

3

In [15]:
TENSOR.shape

torch.Size([1, 3, 3])

###### Lets create one more tensor and expiramend with the ndim , shape and the indexing

In [16]:
MYTENSOR = torch.tensor([[[1,2,3],[5,6,8],[2,5,6]],[[4,2,3],[5,66,8],[2,5,6]]])

In [17]:
MYTENSOR.shape

torch.Size([2, 3, 3])

In [18]:
MYTENSOR.ndim

3

In [19]:
MYTENSOR[0]

tensor([[1, 2, 3],
        [5, 6, 8],
        [2, 5, 6]])

In [20]:
MYTENSOR[1]

tensor([[ 4,  2,  3],
        [ 5, 66,  8],
        [ 2,  5,  6]])

In [21]:
MYTENSOR[1,1]

tensor([ 5, 66,  8])

### Random tensors

Random tensors are important because many neural networks:

-start with random numbers
-look at data
-update random numbers
-look at data
-update

In [22]:
# create random tensor size (3,4)

random_tensor = torch.rand(3,4)
random_tensor

tensor([[0.1019, 0.9789, 0.5924, 0.7655],
        [0.3269, 0.0632, 0.3851, 0.2062],
        [0.3493, 0.9327, 0.3028, 0.7776]])

In [23]:
random_tensor.ndim

2

In [24]:
random_tensor.shape

torch.Size([3, 4])

In [25]:
# Create a random tensor with similar shape to an image tensor
random_image_size_tensor = torch.rand(size=(224,224,3)) # height,width , color channels (R,G,B)
random_image_size_tensor

tensor([[[0.3426, 0.2813, 0.1326],
         [0.5062, 0.2244, 0.4301],
         [0.0510, 0.6748, 0.3066],
         ...,
         [0.6906, 0.2122, 0.8620],
         [0.4996, 0.0172, 0.9616],
         [0.5711, 0.9955, 0.1924]],

        [[0.2455, 0.3881, 0.5250],
         [0.9644, 0.7069, 0.6361],
         [0.2218, 0.1849, 0.3464],
         ...,
         [0.3768, 0.2717, 0.2332],
         [0.9344, 0.0770, 0.8455],
         [0.0788, 0.2635, 0.4002]],

        [[0.9636, 0.2908, 0.9174],
         [0.3050, 0.6083, 0.5826],
         [0.6902, 0.9467, 0.7004],
         ...,
         [0.9953, 0.0302, 0.6927],
         [0.7121, 0.4155, 0.3091],
         [0.7967, 0.3709, 0.9819]],

        ...,

        [[0.0240, 0.2817, 0.2539],
         [0.9896, 0.3017, 0.8284],
         [0.5848, 0.2766, 0.8452],
         ...,
         [0.7094, 0.9827, 0.9603],
         [0.7870, 0.2737, 0.5417],
         [0.8938, 0.3606, 0.5002]],

        [[0.2183, 0.7177, 0.1101],
         [0.8109, 0.5312, 0.3409],
         [0.

In [26]:
random_image_size_tensor.shape , random_image_size_tensor.ndim

(torch.Size([224, 224, 3]), 3)

In [27]:
# lets create my own random tensor

myrandom_tensor = torch.rand(34,3,3,43)
myrandom_tensor

tensor([[[[0.4518, 0.4137, 0.2294,  ..., 0.8359, 0.2085, 0.4510],
          [0.1851, 0.4969, 0.5585,  ..., 0.8311, 0.3628, 0.1894],
          [0.4556, 0.5305, 0.1036,  ..., 0.8341, 0.2885, 0.8794]],

         [[0.6776, 0.9416, 0.8386,  ..., 0.8900, 0.2310, 0.1762],
          [0.8881, 0.9279, 0.1553,  ..., 0.9000, 0.4662, 0.9562],
          [0.0370, 0.5624, 0.2977,  ..., 0.3296, 0.7504, 0.0946]],

         [[0.1685, 0.5049, 0.8133,  ..., 0.7867, 0.1938, 0.8936],
          [0.4020, 0.2584, 0.7552,  ..., 0.4728, 0.4757, 0.4365],
          [0.6898, 0.5972, 0.1817,  ..., 0.8559, 0.7356, 0.9300]]],


        [[[0.5671, 0.1837, 0.0283,  ..., 0.8269, 0.8795, 0.2924],
          [0.3434, 0.9990, 0.3692,  ..., 0.4878, 0.7198, 0.3606],
          [0.8250, 0.4764, 0.5392,  ..., 0.9563, 0.9649, 0.6370]],

         [[0.5557, 0.9306, 0.7143,  ..., 0.5806, 0.8904, 0.6176],
          [0.1703, 0.0476, 0.8959,  ..., 0.2328, 0.1238, 0.6540],
          [0.8108, 0.0814, 0.9626,  ..., 0.2114, 0.0553, 0.0905]],

In [28]:
myrandom_tensor.shape , myrandom_tensor.ndim

(torch.Size([34, 3, 3, 43]), 4)

# ZEROS AND ONES

In [29]:
ZEROS_TENSOR = torch.zeros(size =(2,3))
ZEROS_TENSOR

tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [30]:
ONES_TENSOR = torch.ones(2,3)
ONES_TENSOR , ONES_TENSOR.dtype

(tensor([[1., 1., 1.],
         [1., 1., 1.]]),
 torch.float32)

### Creating a range of tensors and tensors-like

In [31]:
# Lets use torch.arange() the old functions was range()

one_to_ten = torch.arange(start=1,end= 11)
one_to_ten

tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [32]:
with_steps = torch.arange(start=1,end= 11 , step= 3)
with_steps

tensor([ 1,  4,  7, 10])

In [33]:
# Creating tensors  like

ten_zeros = torch.zeros_like(input=one_to_ten)
ten_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

### Tensor datatypes

In [34]:
# Float 32 tensor
# When a number takes less memory , you can calculate faster ,
# when a number is larger you can calculate more acurate


float_32_tensor = torch.tensor([3.0,6.0,9.0], dtype=None, # What datatype is the tensor
                               device=None, # What device is your tensor
                               requires_grad=False) # whether or not to track gradients with this tensors operations
float_32_tensor

tensor([3., 6., 9.])

In [35]:
float_16_tensor = float_32_tensor.type(torch.float16)
float_16_tensor

tensor([3., 6., 9.], dtype=torch.float16)

In [36]:
# sometimes it works but not every time , in this case it works
float_16_tensor * float_32_tensor

tensor([ 9., 36., 81.])

### Getting inforamation from tensors

1. if tensor is not right datatype - tensor.dtype
2. if tensor not right shape - tensor.shape
3. if tensor not on the right device - tensor.device

In [37]:
# Creating a tensor

some_tensor = torch.rand(3,4)
some_tensor

tensor([[0.4850, 0.5913, 0.7511, 0.2575],
        [0.0602, 0.2061, 0.3508, 0.3094],
        [0.4812, 0.6330, 0.5203, 0.5143]])

In [38]:
# Find out details about the tensor
print(some_tensor)
print(f"Datatype of tensor: {some_tensor.dtype}")
print(f"Shape of tensor: {some_tensor.shape} Its also the same thing with the function size() {some_tensor.size()}")
print(f"Device tensor is on: {some_tensor.device}")

tensor([[0.4850, 0.5913, 0.7511, 0.2575],
        [0.0602, 0.2061, 0.3508, 0.3094],
        [0.4812, 0.6330, 0.5203, 0.5143]])
Datatype of tensor: torch.float32
Shape of tensor: torch.Size([3, 4]) Its also the same thing with the function size() torch.Size([3, 4])
Device tensor is on: cpu


In [39]:
some_tensor.cuda()
print(f"Device tensor is on: {some_tensor.device}")

Device tensor is on: cpu


In [40]:
!nvidia-smi

Fri Jul 18 16:15:31 2025       
+-----------------------------------------------------------------------------------------+
| NVIDIA-SMI 550.54.15              Driver Version: 550.54.15      CUDA Version: 12.4     |
|-----------------------------------------+------------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id          Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |           Memory-Usage | GPU-Util  Compute M. |
|                                         |                        |               MIG M. |
|=========================================+========================+======================|
|   0  Tesla T4                       Off |   00000000:00:04.0 Off |                    0 |
| N/A   66C    P0             34W /   70W |     104MiB /  15360MiB |      3%      Default |
|                                         |                        |                  N/A |
+-----------------------------------------+-----

In [ ]:
int_32_tensor = torch.tensor([3,6,9],dtype=torch.int64)
int_32_tensor