<a href="https://colab.research.google.com/github/AndrewDem04/pyTorch_fundamentals/blob/main/00_pyTorch_fundamentals.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import torch
print(torch.__version__)

2.6.0+cu124


## Introduction to Tensors


### scaral

In [3]:
# we have difrente types of tensors
#You must see the -- torch.tensor documentation and what tensor is
# scaral

scalar = torch.tensor(7)
scalar.item()

7

### vector

In [4]:
# vector
vector = torch.tensor([7,7])
vector

tensor([7, 7])

In [5]:
# how meny dimension it have --ndim
vector.ndim

1

In [6]:
vector.shape

torch.Size([2])

In [7]:
MATRIX = torch.tensor([[7,8],[9,10]])

In [8]:
MATRIX.ndim

2

In [9]:
MATRIX[1]

tensor([ 9, 10])

In [10]:
MATRIX.shape

torch.Size([2, 2])

In [11]:
TENSOR = torch.tensor([[[1,2,3],[4,5,6],[7,8,9]]])

In [12]:
TENSOR.ndim

3

In [13]:
TENSOR.shape

torch.Size([1, 3, 3])

###### Lets create one more tensor and expiramend with the ndim , shape and the indexing

In [14]:
MYTENSOR = torch.tensor([[[1,2,3],[5,6,8],[2,5,6]],[[4,2,3],[5,66,8],[2,5,6]]])

In [15]:
MYTENSOR.shape

torch.Size([2, 3, 3])

In [16]:
MYTENSOR.ndim

3

In [17]:
MYTENSOR[0]

tensor([[1, 2, 3],
        [5, 6, 8],
        [2, 5, 6]])

In [18]:
MYTENSOR[1]

tensor([[ 4,  2,  3],
        [ 5, 66,  8],
        [ 2,  5,  6]])

In [19]:
MYTENSOR[1,1]

tensor([ 5, 66,  8])

### Random tensors

Random tensors are important because many neural networks:

-start with random numbers
-look at data
-update random numbers
-look at data
-update

In [20]:
# create random tensor size (3,4)

random_tensor = torch.rand(3,4)
random_tensor

tensor([[0.9781, 0.5654, 0.9773, 0.9518],
        [0.2645, 0.0433, 0.3775, 0.0219],
        [0.8220, 0.8200, 0.3239, 0.9106]])

In [21]:
random_tensor.ndim

2

In [22]:
random_tensor.shape

torch.Size([3, 4])

In [23]:
# Create a random tensor with similar shape to an image tensor
random_image_size_tensor = torch.rand(size=(224,224,3)) # height,width , color channels (R,G,B)
random_image_size_tensor

tensor([[[0.0837, 0.6974, 0.4782],
         [0.5916, 0.3472, 0.2837],
         [0.9470, 0.9040, 0.0347],
         ...,
         [0.2001, 0.8739, 0.8278],
         [0.1003, 0.8602, 0.7129],
         [0.7317, 0.7285, 0.4507]],

        [[0.1567, 0.4737, 0.8002],
         [0.3308, 0.7589, 0.3945],
         [0.3409, 0.2819, 0.6568],
         ...,
         [0.1081, 0.0824, 0.0425],
         [0.5112, 0.4941, 0.1260],
         [0.6100, 0.5976, 0.0069]],

        [[0.4490, 0.9917, 0.2049],
         [0.1445, 0.1477, 0.9537],
         [0.9334, 0.4729, 0.0622],
         ...,
         [0.4041, 0.1294, 0.4136],
         [0.2436, 0.5430, 0.3652],
         [0.4241, 0.6866, 0.3009]],

        ...,

        [[0.7911, 0.4747, 0.5190],
         [0.5206, 0.7661, 0.7340],
         [0.3477, 0.0561, 0.9164],
         ...,
         [0.2914, 0.4776, 0.0689],
         [0.6121, 0.3263, 0.1638],
         [0.9710, 0.1909, 0.8363]],

        [[0.7621, 0.5206, 0.9958],
         [0.4666, 0.3075, 0.4085],
         [0.

In [24]:
random_image_size_tensor.shape , random_image_size_tensor.ndim

(torch.Size([224, 224, 3]), 3)

In [25]:
# lets create my own random tensor

myrandom_tensor = torch.rand(34,3,3,43)
myrandom_tensor

tensor([[[[0.7422, 0.7265, 0.3644,  ..., 0.1658, 0.9287, 0.8795],
          [0.1114, 0.7350, 0.1785,  ..., 0.4348, 0.9180, 0.1070],
          [0.6989, 0.3054, 0.2082,  ..., 0.0284, 0.9259, 0.7216]],

         [[0.9576, 0.3427, 0.7201,  ..., 0.2317, 0.4055, 0.2724],
          [0.7115, 0.9390, 0.0978,  ..., 0.8225, 0.5768, 0.0945],
          [0.3983, 0.2050, 0.3527,  ..., 0.5748, 0.1978, 0.0590]],

         [[0.3972, 0.1049, 0.6943,  ..., 0.9789, 0.9353, 0.3313],
          [0.7390, 0.1335, 0.3133,  ..., 0.9947, 0.2873, 0.5611],
          [0.6746, 0.9591, 0.2863,  ..., 0.5523, 0.3564, 0.0913]]],


        [[[0.2768, 0.1303, 0.9693,  ..., 0.8958, 0.0880, 0.7107],
          [0.0359, 0.7959, 0.8145,  ..., 0.7688, 0.7937, 0.1785],
          [0.7953, 0.5978, 0.8338,  ..., 0.2149, 0.9199, 0.1873]],

         [[0.9827, 0.8790, 0.4784,  ..., 0.9859, 0.2411, 0.5571],
          [0.8288, 0.3922, 0.9993,  ..., 0.2548, 0.2030, 0.1956],
          [0.2151, 0.3819, 0.8283,  ..., 0.5982, 0.5571, 0.4158]],

In [26]:
myrandom_tensor.shape , myrandom_tensor.ndim

(torch.Size([34, 3, 3, 43]), 4)

# ZEROS AND ONES

In [27]:
ZEROS_TENSOR = torch.zeros(size =(2,3))
ZEROS_TENSOR

tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [28]:
ONES_TENSOR = torch.ones(2,3)
ONES_TENSOR , ONES_TENSOR.dtype

(tensor([[1., 1., 1.],
         [1., 1., 1.]]),
 torch.float32)

### Creating a range of tensors and tensors-like

In [29]:
# Lets use torch.arange() the old functions was range()

one_to_ten = torch.arange(start=1,end= 11)
one_to_ten

tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [30]:
with_steps = torch.arange(start=1,end= 11 , step= 3)
with_steps

tensor([ 1,  4,  7, 10])

In [31]:
# Creating tensors  like

ten_zeros = torch.zeros_like(input=one_to_ten)
ten_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

### Tensor datatypes

In [34]:
# Float 32 tensor
# When a number takes less memory , you can calculate faster ,
# when a number is larger you can calculate more acurate


float_32_tensor = torch.tensor([3.0,6.0,9.0], dtype=None, # What datatype is the tensor
                               device=None, # What device is your tensor
                               requires_grad=False) # whether or not to track gradients with this tensors operations
float_32_tensor

tensor([3., 6., 9.])

In [36]:
float_16_tensor = float_32_tensor.type(torch.float16)
float_16_tensor

tensor([3., 6., 9.], dtype=torch.float16)

In [37]:
# sometimes it works but not evry time , in this case it works
float_16_tensor * float_32_tensor

tensor([ 9., 36., 81.])