<a href="https://colab.research.google.com/github/AndrewDem04/pyTorch_fundamentals/blob/main/00_pyTorch_fundamentals.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import torch
print(torch.__version__)

2.6.0+cu124


## Introduction to Tensors


### scaral

In [3]:
# we have difrente types of tensors
#You must see the -- torch.tensor documentation and what tensor is
# scaral

scalar = torch.tensor(7)
scalar.item()

7

### vector

In [4]:
# vector
vector = torch.tensor([7,7])
vector

tensor([7, 7])

In [5]:
# how meny dimension it have --ndim
vector.ndim

1

In [6]:
vector.shape

torch.Size([2])

In [7]:
MATRIX = torch.tensor([[7,8],[9,10]])

In [8]:
MATRIX.ndim

2

In [9]:
MATRIX[1]

tensor([ 9, 10])

In [10]:
MATRIX.shape

torch.Size([2, 2])

In [11]:
TENSOR = torch.tensor([[[1,2,3],[4,5,6],[7,8,9]]])

In [12]:
TENSOR.ndim

3

In [13]:
TENSOR.shape

torch.Size([1, 3, 3])

###### Lets create one more tensor and expiramend with the ndim , shape and the indexing

In [14]:
MYTENSOR = torch.tensor([[[1,2,3],[5,6,8],[2,5,6]],[[4,2,3],[5,66,8],[2,5,6]]])

In [15]:
MYTENSOR.shape

torch.Size([2, 3, 3])

In [16]:
MYTENSOR.ndim

3

In [17]:
MYTENSOR[0]

tensor([[1, 2, 3],
        [5, 6, 8],
        [2, 5, 6]])

In [18]:
MYTENSOR[1]

tensor([[ 4,  2,  3],
        [ 5, 66,  8],
        [ 2,  5,  6]])

In [19]:
MYTENSOR[1,1]

tensor([ 5, 66,  8])

### Random tensors

Random tensors are important because many neural networks:

-start with random numbers
-look at data
-update random numbers
-look at data
-update

In [20]:
# create random tensor size (3,4)

random_tensor = torch.rand(3,4)
random_tensor

tensor([[0.7221, 0.2619, 0.3015, 0.7269],
        [0.3837, 0.1236, 0.7131, 0.8865],
        [0.8156, 0.9544, 0.1598, 0.6717]])

In [21]:
random_tensor.ndim

2

In [22]:
random_tensor.shape

torch.Size([3, 4])

In [23]:
# Create a random tensor with similar shape to an image tensor
random_image_size_tensor = torch.rand(size=(224,224,3)) # height,width , color channels (R,G,B)
random_image_size_tensor

tensor([[[0.5053, 0.4427, 0.9188],
         [0.3890, 0.2262, 0.7312],
         [0.0402, 0.4615, 0.0873],
         ...,
         [0.4730, 0.2077, 0.0154],
         [0.0024, 0.6338, 0.4103],
         [0.8297, 0.4120, 0.3347]],

        [[0.7553, 0.6535, 0.9922],
         [0.9151, 0.1958, 0.0287],
         [0.0426, 0.2262, 0.3161],
         ...,
         [0.0415, 0.7758, 0.1229],
         [0.7767, 0.5418, 0.9416],
         [0.9376, 0.0186, 0.1287]],

        [[0.6498, 0.8641, 0.3622],
         [0.9529, 0.9508, 0.0360],
         [0.1036, 0.6355, 0.7108],
         ...,
         [0.1208, 0.2727, 0.7794],
         [0.5172, 0.0406, 0.9171],
         [0.9592, 0.2551, 0.7165]],

        ...,

        [[0.5004, 0.1921, 0.4585],
         [0.8653, 0.0957, 0.3175],
         [0.7562, 0.2440, 0.6394],
         ...,
         [0.5014, 0.0603, 0.6152],
         [0.7477, 0.2894, 0.6790],
         [0.2386, 0.1278, 0.1099]],

        [[0.8166, 0.9648, 0.9898],
         [0.6251, 0.7802, 0.1240],
         [0.

In [24]:
random_image_size_tensor.shape , random_image_size_tensor.ndim

(torch.Size([224, 224, 3]), 3)

In [25]:
# lets create my own random tensor

myrandom_tensor = torch.rand(34,3,3,43)
myrandom_tensor

tensor([[[[0.5400, 0.5592, 0.1757,  ..., 0.3568, 0.6512, 0.9341],
          [0.4017, 0.1306, 0.8263,  ..., 0.7383, 0.3246, 0.2688],
          [0.0614, 0.1304, 0.8063,  ..., 0.2564, 0.2328, 0.3964]],

         [[0.5472, 0.7516, 0.6080,  ..., 0.9003, 0.0519, 0.3864],
          [0.1808, 0.4297, 0.5317,  ..., 0.4950, 0.1075, 0.4025],
          [0.8208, 0.4657, 0.4270,  ..., 0.9980, 0.4857, 0.4651]],

         [[0.3995, 0.2905, 0.2719,  ..., 0.0680, 0.7806, 0.7670],
          [0.8779, 0.7380, 0.9933,  ..., 0.2037, 0.6365, 0.1792],
          [0.5053, 0.1198, 0.7038,  ..., 0.0509, 0.1605, 0.5316]]],


        [[[0.2488, 0.3440, 0.2350,  ..., 0.4840, 0.0521, 0.7279],
          [0.7388, 0.1980, 0.0762,  ..., 0.8777, 0.3411, 0.1569],
          [0.4054, 0.7960, 0.8277,  ..., 0.3806, 0.1358, 0.3420]],

         [[0.5915, 0.6919, 0.3320,  ..., 0.0396, 0.0104, 0.0854],
          [0.1651, 0.7973, 0.9089,  ..., 0.8114, 0.9253, 0.5773],
          [0.6219, 0.1654, 0.8144,  ..., 0.6605, 0.1704, 0.2360]],

In [26]:
myrandom_tensor.shape , myrandom_tensor.ndim

(torch.Size([34, 3, 3, 43]), 4)

# ZEROS AND ONES

In [27]:
ZEROS_TENSOR = torch.zeros(size =(2,3))
ZEROS_TENSOR

tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [28]:
ONES_TENSOR = torch.ones(2,3)
ONES_TENSOR , ONES_TENSOR.dtype

(tensor([[1., 1., 1.],
         [1., 1., 1.]]),
 torch.float32)

### Creating a range of tensors and tensors-like

In [29]:
# Lets use torch.arange() the old functions was range()

one_to_ten = torch.arange(start=1,end= 11)
one_to_ten

tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [30]:
with_steps = torch.arange(start=1,end= 11 , step= 3)
with_steps

tensor([ 1,  4,  7, 10])

In [31]:
# Creating tensors  like

ten_zeros = torch.zeros_like(input=one_to_ten)
ten_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

### Tensor datatypes

In [32]:
# Float 32 tensor
# When a number takes less memory , you can calculate faster ,
# when a number is larger you can calculate more acurate


float_32_tensor = torch.tensor([3.0,6.0,9.0], dtype=None, # What datatype is the tensor
                               device=None, # What device is your tensor
                               requires_grad=False) # whether or not to track gradients with this tensors operations
float_32_tensor

tensor([3., 6., 9.])

In [33]:
float_16_tensor = float_32_tensor.type(torch.float16)
float_16_tensor

tensor([3., 6., 9.], dtype=torch.float16)

In [34]:
# sometimes it works but not every time , in this case it works
float_16_tensor * float_32_tensor

tensor([ 9., 36., 81.])

### Getting inforamation from tensors

1. if tensor is not right datatype - tensor.dtype
2. if tensor not right shape - tensor.shape
3. if tensor not on the right device - tensor.device

In [35]:
# Creating a tensor

some_tensor = torch.rand(3,4)
some_tensor

tensor([[0.6066, 0.7142, 0.1214, 0.9720],
        [0.2823, 0.8030, 0.3070, 0.8768],
        [0.4131, 0.3175, 0.9247, 0.9239]])

In [36]:
# Find out details about the tensor
print(some_tensor)
print(f"Datatype of tensor: {some_tensor.dtype}")
print(f"Shape of tensor: {some_tensor.shape} Its also the same thing with the function size() {some_tensor.size()}")
print(f"Device tensor is on: {some_tensor.device}")

tensor([[0.6066, 0.7142, 0.1214, 0.9720],
        [0.2823, 0.8030, 0.3070, 0.8768],
        [0.4131, 0.3175, 0.9247, 0.9239]])
Datatype of tensor: torch.float32
Shape of tensor: torch.Size([3, 4]) Its also the same thing with the function size() torch.Size([3, 4])
Device tensor is on: cpu


In [42]:
some_tensor.cuda()
print(f"Device tensor is on: {some_tensor.device}")

Device tensor is on: cpu


In [43]:
!nvidia

/bin/bash: line 1: nvidia: command not found
